spring:
  application:
    name: study1
  datasource:
    url: jdbc:mysql://localhost:3306/mmo_market
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sa123
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
jwt:
  secret-key: "nVhBcHbv71BB6bdjaopOoa4LWx/tjz9c7wBREJdpLU7O+EQBGH3Np+PmgDpMziH4zLGbqtt9CWDPbVwToH/cGyDbZeIJ5rUsL1MAeVs0ER0="

