spring:
  application:
    name: study1
  datasource:
    url: jdbc:mysql://localhost:3306/mmo_market
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mvc:
    async:
      request-timeout: 5000ms
  task:
    scheduling:
      enabled: true
      pool:
        size: 2
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-durations-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      fail-on-invalid-subtype: false
      use-long-for-ints: true
      use-big-decimal-for-floats: false
    time-zone: Asia/Ho_Chi_Minh
    # Force enable JSR310 module
    modules:
      - com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: dat2801zz@gmail.com
    password: yoxh secc lerq ykat # <-- See security note below
    from: dat2801zz@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "84371119573-vd16u13p71e77ies0bch5d47n1c9fubs.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/auth"
            token-uri: "https://oauth2.googleapis.com/token"
            user-info-uri: "https://www.googleapis.com/oauth2/v2/userinfo"
            user-name-attribute: "id"
jwt:
  secret-key: "nVhBcHbv71BB6bdjaopOoa4LWx/tjz9c7wBREJdpLU7O+EQBGH3Np+PmgDpMziH4zLGbqtt9CWDPbVwToH/cGyDbZeIJ5rUsL1MAeVs0ER0="

# Security Configuration
security:
  captcha:
    expire-minutes: 5
    length: 6
  rate-limit:
    ip-max-attempts: 10
    ip-lockout-minutes: 30
    captcha-required-attempts: 3
    email-max-requests-per-hour: 3
    otp-max-attempts: 5
    otp-expire-minutes: 10


  

vnpay:
  url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "http://localhost:8080/payment/return"
  tmn-code: "WFNMT41C"
  secret-key: "GEGAKB9OUVUZFVVMOB5YNTSVBY1IWKTC"
  version: "2.1.0"
  command: "pay"
  order-type: "other"
  locale: "vn"
  currency-code: "VND"
logging:
  level:
    com.badat.study1: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
server:
  port: 8080
  tomcat:
    connection-timeout: 30000
    max-connections: 8192
    accept-count: 100
    threads:
      max: 200
      min-spare: 10