spring:
  application:
    name: study1
  datasource:
    url: jdbc:mysql://localhost:3306/mmo_market
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dat2801zz@gmail.com
    password: yoxh secc lerq ykat # <-- See security note below
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/
      cache:
        period: 0
jwt:
  secret-key: "nVhBcHbv71BB6bdjaopOoa4LWx/tjz9c7wBREJdpLU7O+EQBGH3Np+PmgDpMziH4zLGbqtt9CWDPbVwToH/cGyDbZeIJ5rUsL1MAeVs0ER0="

vnpay:
  url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "http://localhost:8080/payment/return"
  tmn-code: "WFNMT41C"
  secret-key: "GEGAKB9OUVUZFVVMOB5YNTSVBY1IWKTC"
  version: "2.1.0"
  command: "pay"
  order-type: "other"
  locale: "vn"
  currency-code: "VND"
logging:
  level:
    com.badat.study1.configuration.JwtAuthenticationFilter: DEBUG
    com.badat.study1.controller.ViewController: DEBUG
    com.badat.study1.service.JwtService: DEBUG
    com.badat.study1.service.AuthenticationService: DEBUG