spring:
  application:
    name: study1
  datasource:
    url: jdbc:mysql://localhost:3306/mmo_market
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sa123
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        host: smtp.gmail.com
        port: 587
        username: dat2801zz@gmail.com
        # Dán mật khẩu 16 ký tự vào đây
        password: yoxh secc lerq ykat
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
jwt:
  secret-key: "nVhBcHbv71BB6bdjaopOoa4LWx/tjz9c7wBREJdpLU7O+EQBGH3Np+PmgDpMziH4zLGbqtt9CWDPbVwToH/cGyDbZeIJ5rUsL1MAeVs0ER0="

vnpay:
  url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "http://localhost:8080/payment/return"
  tmn-code: "WFNMT41C"
  secret-key: "GEGAKB9OUVUZFVVMOB5YNTSVBY1IWKTC"
  version: "2.1.0"
  command: "pay"
  order-type: "other"
  locale: "vn"
  currency-code: "VND"